name: Colcon build and test

on: [pull_request]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.0.25
      - uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: ros_ci_lab
          target-ros2-distro: foxy
          vcs-repo-file-url: ""
